// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbtmbgiuzccgowrczfhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5idG1iZ2l1emNjZ293cmN6Zmh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDU0NzcsImV4cCI6MjA3MDY4MTQ3N30.b1cXTvLXCXdFwBUwM9VHXwWJ4TPSk3h4YumZzf7gueM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});